"""add coupon model

Revision ID: 7f8g9h0i1j2k
Revises: 5ca9ff90be31
Create Date: 2025-11-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8g9h0i1j2k'
down_revision = '5ca9ff90be31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create coupon table
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('coupon_type', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_date', sa.DateTime(), nullable=True),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_code'), 'coupon', ['code'], unique=True)
    
    # Add new columns to ticket table
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('coupon_code', sa.String(length=64), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove columns from ticket table
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('coupon_code')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('original_price')
    
    # Drop coupon table
    op.drop_index(op.f('ix_coupon_code'), table_name='coupon')
    op.drop_table('coupon')
    
    # ### end Alembic commands ###
