"""add vip membership and level system

Revision ID: d87b0318846b
Revises: 0a2afc9c5d47
Create Date: 2025-11-19 02:02:19.105252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87b0318846b'
down_revision = '0a2afc9c5d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vip_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('vip_expiry')
        batch_op.drop_column('vip_type')

    # ### end Alembic commands ###
