"""add auto_renew_vip field

Revision ID: f1a16545eaa6
Revises: d23e7331c11c
Create Date: 2025-11-19 02:22:04.203631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a16545eaa6'
down_revision = 'd23e7331c11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_renew_vip', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auto_renew_vip')

    # ### end Alembic commands ###
